version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: biubiustar-app
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${APP_PORT:-3000}
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - MEMORY_LIMIT=${MEMORY_LIMIT:-512}
      - ENABLE_CACHE=${ENABLE_CACHE:-true}
    volumes:
      - ./uploads:/app/public/uploads:ro
      - ./logs:/app/logs
      - ./backups:/app/backups
    restart: unless-stopped
    networks:
      - biubiustar-network
    # 单机内存优化配置
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-1G}
          cpus: '1.0'
        reservations:
          memory: ${MEMORY_LIMIT:-512M}
          cpus: '0.5'
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${HEALTH_CHECK_PORT:-3000}/api/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
      start_period: ${HEALTH_CHECK_START_PERIOD:-40s}
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILES:-3}
    # 环境变量优化
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    container_name: biubiustar-nginx
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./uploads:/var/www/uploads:ro
      - ./dist:/var/www/dist:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - biubiustar-network
    # 单机资源优化
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    # 健康检查
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: ${HEALTH_CHECK_INTERVAL:-30s}
      timeout: ${HEALTH_CHECK_TIMEOUT:-10s}
      retries: ${HEALTH_CHECK_RETRIES:-3}
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: ${LOG_MAX_SIZE:-10m}
        max-file: ${LOG_MAX_FILES:-3}

  # 备份服务 (简化版)
  backup:
    image: alpine:latest
    container_name: biubiustar-backup
    volumes:
      - ./backups:/backups
      - ./uploads:/uploads:ro
      - ./logs:/logs:ro
    command: >
      sh -c "
        echo '开始备份...' &&
        # 备份上传文件和日志
        tar -czf /backups/uploads-$$(date +%Y%m%d-%H%M%S).tar.gz /uploads &&
        tar -czf /backups/logs-$$(date +%Y%m%d-%H%M%S).tar.gz /logs &&
        echo '备份完成' &&
        # 清理指定天数前的备份文件
        find /backups -name '*-*.tar.gz' -mtime +${BACKUP_RETENTION_DAYS:-7} -delete &&
        echo '清理${BACKUP_RETENTION_DAYS:-7}天前的备份文件' &&
        # 压缩备份文件以节省空间
        find /backups -name '*.tar.gz' -mtime +1 -exec gzip -${BACKUP_COMPRESSION_LEVEL:-6} {} \;
      "
    restart: "no"
    networks:
      - biubiustar-network

volumes:
  uploads:

networks:
  biubiustar-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
