-- Reset content categories with multilingual data for zh, zh-TW, en, vi
-- This migration resets the content_categories table with proper multilingual support

-- Clear existing content categories data
DELETE FROM content_categories;

-- Reset the sequence-- 注意：content_categories表使用UUID主键，无需重置序列 Insert content categories with multilingual data
INSERT INTO content_categories (
  name, 
  description, 
  color, 
  icon, 
  is_active,
  name_zh, 
  name_zh_tw, 
  name_en, 
  name_vi,
  description_zh, 
  description_zh_tw, 
  description_en, 
  description_vi
) VALUES 
(
  '技术分享', 
  '分享技术知识、编程经验、开发心得等技术相关内容', 
  '#3B82F6', 
  'code', 
  true,
  '技术分享',
  '技術分享',
  'Tech Sharing',
  'Chia sẻ Công nghệ',
  '分享技术知识、编程经验、开发心得等技术相关内容',
  '分享技術知識、程式設計經驗、開發心得等技術相關內容',
  'Share technical knowledge, programming experience, development insights and other tech-related content',
  'Chia sẻ kiến thức kỹ thuật, kinh nghiệm lập trình, hiểu biết phát triển và nội dung liên quan đến công nghệ khác'
),
(
  '生活分享', 
  '分享日常生活、生活感悟、生活技巧等生活相关内容', 
  '#10B981', 
  'heart', 
  true,
  '生活分享',
  '生活分享',
  'Life Sharing',
  'Chia sẻ Cuộc sống',
  '分享日常生活、生活感悟、生活技巧等生活相关内容',
  '分享日常生活、生活感悟、生活技巧等生活相關內容',
  'Share daily life, life insights, life tips and other life-related content',
  'Chia sẻ cuộc sống hàng ngày, cảm nhận về cuộc sống, mẹo sống và nội dung liên quan đến cuộc sống khác'
),
(
  '学习交流', 
  '分享学习心得、学习方法、知识总结等学习相关内容', 
  '#8B5CF6', 
  'book-open', 
  true,
  '学习交流',
  '學習交流',
  'Learning Exchange',
  'Trao đổi Học tập',
  '分享学习心得、学习方法、知识总结等学习相关内容',
  '分享學習心得、學習方法、知識總結等學習相關內容',
  'Share learning experiences, study methods, knowledge summaries and other learning-related content',
  'Chia sẻ kinh nghiệm học tập, phương pháp học tập, tóm tắt kiến thức và nội dung liên quan đến học tập khác'
),
(
  '兴趣爱好', 
  '分享个人兴趣、爱好体验、收藏心得等兴趣相关内容', 
  '#F59E0B', 
  'star', 
  true,
  '兴趣爱好',
  '興趣愛好',
  'Hobbies & Interests',
  'Sở thích & Quan tâm',
  '分享个人兴趣、爱好体验、收藏心得等兴趣相关内容',
  '分享個人興趣、愛好體驗、收藏心得等興趣相關內容',
  'Share personal interests, hobby experiences, collection insights and other interest-related content',
  'Chia sẻ sở thích cá nhân, trải nghiệm sở thích, hiểu biết sưu tập và nội dung liên quan đến sở thích khác'
),
(
  '旅行游记', 
  '分享旅行经历、旅游攻略、景点推荐等旅行相关内容', 
  '#06B6D4', 
  'map-pin', 
  true,
  '旅行游记',
  '旅行遊記',
  'Travel Journal',
  'Nhật ký Du lịch',
  '分享旅行经历、旅游攻略、景点推荐等旅行相关内容',
  '分享旅行經歷、旅遊攻略、景點推薦等旅行相關內容',
  'Share travel experiences, travel guides, attraction recommendations and other travel-related content',
  'Chia sẻ trải nghiệm du lịch, hướng dẫn du lịch, đề xuất điểm tham quan và nội dung liên quan đến du lịch khác'
),
(
  '美食分享', 
  '分享美食体验、烹饪心得、餐厅推荐等美食相关内容', 
  '#EF4444', 
  'utensils', 
  true,
  '美食分享',
  '美食分享',
  'Food Sharing',
  'Chia sẻ Ẩm thực',
  '分享美食体验、烹饪心得、餐厅推荐等美食相关内容',
  '分享美食體驗、烹飪心得、餐廳推薦等美食相關內容',
  'Share food experiences, cooking insights, restaurant recommendations and other food-related content',
  'Chia sẻ trải nghiệm ẩm thực, hiểu biết nấu ăn, đề xuất nhà hàng và nội dung liên quan đến thực phẩm khác'
),
(
  '摄影作品', 
  '分享摄影作品、拍摄技巧、器材心得等摄影相关内容', 
  '#EC4899', 
  'camera', 
  true,
  '摄影作品',
  '攝影作品',
  'Photography',
  'Nhiếp ảnh',
  '分享摄影作品、拍摄技巧、器材心得等摄影相关内容',
  '分享攝影作品、拍攝技巧、器材心得等攝影相關內容',
  'Share photography works, shooting techniques, equipment insights and other photography-related content',
  'Chia sẻ tác phẩm nhiếp ảnh, kỹ thuật chụp, hiểu biết thiết bị và nội dung liên quan đến nhiếp ảnh khác'
),
(
  '音乐艺术', 
  '分享音乐作品、艺术创作、文化体验等艺术相关内容', 
  '#8B5CF6', 
  'music', 
  true,
  '音乐艺术',
  '音樂藝術',
  'Music & Art',
  'Âm nhạc & Nghệ thuật',
  '分享音乐作品、艺术创作、文化体验等艺术相关内容',
  '分享音樂作品、藝術創作、文化體驗等藝術相關內容',
  'Share music works, artistic creations, cultural experiences and other art-related content',
  'Chia sẻ tác phẩm âm nhạc, sáng tạo nghệ thuật, trải nghiệm văn hóa và nội dung liên quan đến nghệ thuật khác'
),
(
  '读书笔记', 
  '分享读书心得、书籍推荐、阅读感悟等阅读相关内容', 
  '#059669', 
  'book', 
  true,
  '读书笔记',
  '讀書筆記',
  'Reading Notes',
  'Ghi chú Đọc sách',
  '分享读书心得、书籍推荐、阅读感悟等阅读相关内容',
  '分享讀書心得、書籍推薦、閱讀感悟等閱讀相關內容',
  'Share reading insights, book recommendations, reading reflections and other reading-related content',
  'Chia sẻ hiểu biết đọc sách, đề xuất sách, suy ngẫm đọc sách và nội dung liên quan đến đọc sách khác'
),
(
  '职场经验', 
  '分享职场心得、工作技巧、职业发展等职场相关内容', 
  '#DC2626', 
  'briefcase', 
  true,
  '职场经验',
  '職場經驗',
  'Career Experience',
  'Kinh nghiệm Nghề nghiệp',
  '分享职场心得、工作技巧、职业发展等职场相关内容',
  '分享職場心得、工作技巧、職業發展等職場相關內容',
  'Share workplace insights, work skills, career development and other career-related content',
  'Chia sẻ hiểu biết nơi làm việc, kỹ năng làm việc, phát triển nghề nghiệp và nội dung liên quan đến nghề nghiệp khác'
),
(
  '健康养生', 
  '分享健康知识、养生心得、运动体验等健康相关内容', 
  '#16A34A', 
  'heart-pulse', 
  true,
  '健康养生',
  '健康養生',
  'Health & Wellness',
  'Sức khỏe & Chăm sóc',
  '分享健康知识、养生心得、运动体验等健康相关内容',
  '分享健康知識、養生心得、運動體驗等健康相關內容',
  'Share health knowledge, wellness insights, exercise experiences and other health-related content',
  'Chia sẻ kiến thức sức khỏe, hiểu biết chăm sóc sức khỏe, trải nghiệm tập thể dục và nội dung liên quan đến sức khỏe khác'
),
(
  '创业分享', 
  '分享创业经历、商业思考、项目经验等创业相关内容', 
  '#EA580C', 
  'rocket', 
  true,
  '创业分享',
  '創業分享',
  'Entrepreneurship',
  'Khởi nghiệp',
  '分享创业经历、商业思考、项目经验等创业相关内容',
  '分享創業經歷、商業思考、項目經驗等創業相關內容',
  'Share entrepreneurial experiences, business thinking, project experiences and other entrepreneurship-related content',
  'Chia sẻ kinh nghiệm khởi nghiệp, tư duy kinh doanh, kinh nghiệm dự án và nội dung liên quan đến khởi nghiệp khác'
);